### ISSUE TITLE
Only returns zeros on Arduino UNO R4

### ISSUE THREAD

**Issue by F-Schmidt99** [sparkfun/SparkFun_AS7331_Arduino_Library#6]
Problem: Only reading zeros

Minimum working example:

```
SfeAS7331ArdI2C sensor;

void setup() {
    Serial.begin(9600);
    Wire.begin();
    if(!sensor.begin()) {
        Serial.println("FAILED INIT");
        while(1);
    }
    sensor.prepareMeasurement(MEAS_MODE_CONT);
    sensor .setStartState(true);
}

void loop() {
    if(sensor.readAll() == kSTkErrOk) {
        Serial.println(sensor.getTemp());
        Serial.println(sensor.getUVA());
        Serial.println(sensor.getUVB());
        Serial.println(sensor.getUVC());
    } else {
        Serial.println("Fail!");
    }
}
```

This code compiles and runs, but it only returns in these output values on serial interface:

-66.90
0.00
0.00
0.00

The -66.9 is the temperature, if the read value from sensor is zero. So basically, all we read from the sensors are zeros for all values, which can not be true. Am I missing something, is there another setup function for the sensor that must be called? I checked all wires, also with other sensors and they totally work. It must be a software related issue!

Logic level converter is used and working (also measured using oscilloscope).

**Comment by SFE-Brudnerd** [comment]
Hi @F-Schmidt99, thanks for submitting this issue. 

Just an FYI, when doing multi-line code you should use 3 ` instead of one, that will make it format correctly.

I have a few recommendations for you to try.
1. Have you had success with some of our examples?
2. Please take a look at the continuous mode example, it uses an interrupt. Based on the code you included above, it doesn't appear that you are. I would recommend using an interrupt or otherwise using one-shot mode.
3. The way you've written your code lends itself more to one shot mode than continuous mode. One-shot mode allows more control over when you take measurements. If you do so, please ensure you delay long enough to allow for the ADC to finish it's measurement.
4. Please read the datasheet and try to set a best guess as to the light intensity range for your application. This is a complex sensor and it's highly configurable. What worked for our example (LED directly over the sensor) might not be a perfect fit for what you're trying to do.
5. Make sure you're setting the break time (time between measurements) in continuous mode. The datasheet says that the sensor is prone to noise from I2C if ADC values are read out during a measurement.
6. Try polling the status register to see if you get any errors.

The temperature value is somewhat curious. Is that a value you expected?

Thanks!

**Comment by F-Schmidt99** [comment]
Hello @SFE-Brudnerd, 
I didn't have luck with any example. Currently I am trying to at least read out the temperature correct. It seems, that the sensor only transfers zeros. According to temperature formula in the datasheet this will return in -66.9 which I get. 

I expect around 20-30 degrees Celsius in the room I am currently in. I changed the program to single shot mode. Is there anything else I need to do? From the examples it does not seem so.

SYN and Interrupt pins are left as they are (floating). I am not using them at all for now.

**Comment by SFE-Brudnerd** [comment]
- What are the return values from `prepareMeasurement` and `setStartState`?
- Do you happen to have another sensor available to test with?
- Are you able to provide a bit more context as to your hardware setup? It seems correct but I just want to double check. 
- Try power cycling the AS7331 then retrying. It's rare and I believe I fixed it, but sometimes the device doesn't restart correctly without a power cycle.
- Since you have a scope available to you, would you please try recording the i2c data and verifying the values you're getting in return?

**Comment by F-Schmidt99** [comment]
@SFE-Brudnerd Both, `prepareMeasurement` and `setStartState` return without error.

No, I do not have another sensor available.

Hardware is correct: I use Arduino I2C pins that are connected with a 5V<->3V3 LLC with SDA and SCL lines. Low voltage side is connected with sensor. The LLC is specifically designed for I2C and it works like a charm (already field-tested). SYN pin and Interrupt are left floating and I do not plan on using them. For my application, polling is fine.

With power cycling, do you mean a hard reset (unplug and plug in again)? I did that several times already.

I can scope later on, currently the device is in use. Can you maybe tell me, if prepareMeasurement and setStartState read and write from the bus? Then we know, that the received values are probably really also transmitted zeros.

At the moment I still think it must be a software problem, because the sensor reacts in all ways to I2C how it should. Using an I2C-scanner it pulls the SDA line down and releases it just as expected. So I do not (yet) believe in a bad sensor. Could you please re-check the software I posted? I have the feeling, that there is a function call missing, maybe some deactivation of power saving or similar?

**Comment by SFE-Brudnerd** [comment]
Ok so with the UNO R4 and a qwiic connector I was able to run your exact example. Please check your hardware connections, but also take a look [here](https://docs.arduino.cc/tutorials/uno-r4-wifi/qwiic/). The qwiic connector uses `Wire1`, so if you're using that, you'll need to modify your script with the following.

```C++
Wire1.begin();

if(!sensor.begin(kDefaultAS7331Addr, Wire1)) {
...
```

What voltage are you powering your AS7331 board with? Please make sure you're using 3.3V, you may damage the device if powered by 5V. The datasheet has this warning listed above the absolute maximum. While it _can_ be exposed to 5V, running it long term will degrade performance.

```
Stresses beyond those listed under “Absolute Maximum Ratings” may cause permanent damage to
the device. These are stress ratings only. Functional operation of the device at these or any other
conditions beyond those indicated under “Operating Conditions” is not implied. Exposure to absolute
maximum rating conditions for extended periods may affect device reliability.
```

If you aren't using the qwiic connector but the headers, in the schematic for the R4 there aren't pull-up resistors populated on the I2C pins. Does your level shifter have pull-up resistors on the 5V side? Our boards have pull-ups on the 3.3V side, so that won't be the issue. If you don't have pull-ups, that could also be causing issues.

Either way, I was able to get your example working on my end with the latest software release from January. I recommend double checking all your connections and pull-ups. Best of luck!
